### ISSUE TITLE
Object Preview Bugged

### ISSUE THREAD

**Issue by Julius-A4** [wafflesgama/LazyFetcher#1]
Hi! Sorry about posting in the wrong place previously.

Ran into some bugs with the object preview window while testing out the package. The background of the window is all red and when I pan the view of the object to a more straight on front profile the whole preview screen goes pink. Im on Unity ver 2022.1.16f1.

![image](https://user-images.githubusercontent.com/45527828/203145989-7dbdeda7-dfc5-42d1-941c-48d918320c24.png)

https://user-images.githubusercontent.com/45527828/203146060-9fcd4080-1ced-4f44-a20e-4c9cbd13c648.mp4

**Comment by wafflesgama** [comment]
Hey again, yup no problem 👌

This seems to be an an issue related to the materials of the preview window not being created for the same pipeline (URP in this case). I'll look into a way of detecting this and change them via script.

Until then, you can change manually the materials under the folder **_LazyBuilder/Data/Materials_**

**Comment by Julius-A4** [comment]
Changing the materials to URP makes it better but part of the background is still red. I had the material on URP Lit. @wafflesgama 

https://user-images.githubusercontent.com/45527828/205704673-1606d2d1-31dc-46da-9cf7-9ce587fcf13a.mp4

**Comment by wafflesgama** [comment]
You're right, it seemed to be a problem with the RenderPreview Utility background color.
It should be fixed in [V1.0.2](https://github.com/wafflesgama/LazyBuilder/releases)
